### ISSUE TITLE
Let's coordinate on improvements?

### ISSUE THREAD

**Issue by motin** [rovest/Bear-Markdown-Export#13]
Hello @rovest,

About 6 weeks ago, I saw some things that didn't work, and some room for improvements, and I made myself confident to understand what the scripts does, tinkered, debugged, fixed and improved. 

The results are in https://github.com/rovest/Bear-Markdown-Export/pull/9 and it includes changes like command line arguments, tests and fixes to many open issues. 

Since then, I have not heard anything from you regarding these changes, and meanwhile, you seem to have partially and in a complete different matter implemented a few of the changes on your own and added new features/changes unrelated to any open issues, making it impossible to merge the above PR without a lot of refactoring. 

If you are interested in coordinating and making both of our efforts help other users of this library, or if you'd rather have this repository reflecting your personal scripts without collaboration from other users, let me know. 

Meanwhile, based on your comment in the README:
> **Please use as is or make a new branch for updates!  
> Thank you all for any input, and sorry that I don't have time to review and test pull requests.**

... I'll continue work on https://github.com/motin/Bear-Markdown-Export instead of updating the PR:s here.

**Comment by motin** [comment]
Some things I'd love to see if we are collaborating on this together:

* Create issues for identified problems that you are working on to fix or have fixed
* One commit per fix/feature/change (currently I see commits that say one thing in the commit message and includes changes and bugfixes that are not mentioned)
* Tests for new improvements where relevant
* One or many PR's that addresses open issues, so that others can comment on and review the PR:s

You can of course still use your PR-branch(es) personally without waiting for feedback and merge to master, but at least this way we can ensure that the master branch is the sum of our efforts and a version that is preferred by all users of this library.

**Comment by rovest** [comment]
@motin 

PS. I have now refactored code and implemented the ‘argparse‘ library.

Thank you very much for all your suggestions, issue reports, and pull requests.

See version 1.7.2 for latest update.

Ha en god dag 😎
Roar
