### ISSUE TITLE
sync copies contents of current working directory into BearNotes folder

### ISSUE THREAD

**Issue by dmd** [rovest/Bear-Markdown-Export#18]
The sync copies the contents of the current working directory into the BearNotes directory!

```

dmd@pico ~/Dropbox/code/Bear-Markdown-Export [master|✔]
$ ls ~/Dropbox/BearNotes
ls: /Users/dmd/Dropbox/BearNotes: No such file or directory

dmd@pico ~/Dropbox/code/Bear-Markdown-Export [master|✔]
$ python bear_export_sync.py
2018-11-19 at 17:45:15 ['bear_export_sync.py']
/Users/dmd/Dropbox/BearNotes
2018-11-19 at 17:45:15 - 6 notes exported to: /Users/dmd/Dropbox/BearNotes

dmd@pico ~/Dropbox/code/Bear-Markdown-Export [master|✔]
$ ls ~/Dropbox/BearNotes/
Bear Import.md      _Untagged           bear_import.py
LICENSE             bear_export_sync.py change_log.md
README.md           bear_export_sync.sh interview
```

**Comment by yoramdelangen** [comment]
I just wanted to open the same issue. Its only on the latest master version.

**Comment by rovest** [comment]
Hi @dmd and @yoramdelangen, thanks for the issue report.

Sorry, I'm not able to reproduce this on my Mac. I have also looked through the code without spotting anything crazy, but it's easy to go blind for obvious bugs, so have to bother you with a few stupid questions to help me debug this issue:

1. I assume you are both running v. 1.7.2 without any internal changes – right?
2. V. 1.7.2 have sync turned off by default ("--do_sync=False"), so should not be related to the sync-back functions, as far as I can see. Or did I miss something here?
3. When I run `$ python bear_export_sync.py` on MacOS 10.14.0, Python 2.7 is called and my script fails.
    - So do you have a shell script starting python3 (if python2.7 is not uninstalled)?  
    - Or any other shortcuts/alias or whatever that could be the cause of this copying? 
4. Would be great if you have time to check if any of my py-code is the culprit.

Thanks a lot,
Roar

**Comment by dmd** [comment]
Roar - You weren't seeing the issue because you're using Carbon Copy Cloner, so for you, crswitch is not empty.

Please merge the attached PR to fix this issue.

**Comment by rovest** [comment]
@dmd Thanks a lot for finding this bug and for your solution.

Great work! Code is now implemented locally, together with some other simplification of the code in this function.

All the best and have a good day/night,
Roar.

**Comment by yoramdelangen** [comment]
Hell yeah! Hadn't time to look into it very closely, but I'm happy you found it @dmd! Thanks!
