### ISSUE TITLE
How to use? Documentation missing detail.

### ISSUE THREAD

**Issue by netgifted** [rovest/Bear-Markdown-Export#3]
I read the documentation but this is not enough for non-programers like me... I installed Python on my mac and did Open to run the script. I get the error message on the Terminal "ImportError: No module named parse"
It would be great to have a Tutorial or a simple paragraph explaining how to run this...
Thanks

**Comment by viktorstrate** [comment]
Make sure you are running python 3

Try running it like this

    $ python3 bear_export_sync.py

If you don't have python 3 installed, you can install it with [Homebrew](https://brew.sh/), by running

    $ brew install python
