### ISSUE TITLE
Original note images with filenames over 196 characters yields `OSError: [Errno 63] File name too long` on export

### ISSUE THREAD

**Issue by motin** [rovest/Bear-Markdown-Export#6]
This happens when an image in one's notes have a long filename (over 196 characters), due to Mac OSX filename limit of 255 characters:

```
$ python Bear-Markdown-Export/bear_export_sync.py
Traceback (most recent call last):
  File "Bear-Markdown-Export/bear_export_sync.py", line 711, in <module>
    main()
  File "Bear-Markdown-Export/bear_export_sync.py", line 120, in main
    note_count = export_markdown()
  File "Bear-Markdown-Export/bear_export_sync.py", line 177, in export_markdown
    make_text_bundle(md_text, filepath, mod_dt)
  File "Bear-Markdown-Export/bear_export_sync.py", line 220, in make_text_bundle
    shutil.copy2(source, target)
  File "/anaconda3/envs/bear-notes-export/lib/python3.6/shutil.py", line 257, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/anaconda3/envs/bear-notes-export/lib/python3.6/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
OSError: [Errno 63] File name too long: '/Users/motin/Temp/BearExportTemp/ts-reported/2017-02-28/note-title-foo.textbundle/assets/D3B5D87D-8FB0-4234-9676-FF79AF6D2CE2-419-000050425B2C8647_averylongfilenameaverylongfilenameaverylongfilenameaverylongfilenameaverylongfilenameaverylongfilenameaverylongfilenameaverylongfilenameaverylongfilenameaverylongfilenameaverylongfilenameaverylongfilenameaverylongfilenameaverylongfilenameav.png'
```

Length of `D3B5D87D-8FB0-4234-9676-FF79AF6D2CE2-419-000050425B2C8647_`: 59
Length of  `averylongfilenameaverylongfilenameaverylongfilenameaverylongfilenameaverylongfilenameaverylongfilenameaverylongfilenameaverylongfilenameaverylongfilenameaverylongfilenameaverylongfilenameaverylongfilenameaverylongfilenameaverylongfilenameav.png`: 245

The original tag was:
```
[image:D3B5D87D-8FB0-4234-9676-FF79AF6D2CE2-419-000050425B2C8647/averylongfilenameaverylongfilenameaverylongfilenameaverylongfilenameaverylongfilenameaverylongfilenameaverylongfilenameaverylongfilenameaverylongfilenameaverylongfilenameaverylongfilenameaverylongfilenameaverylongfilenameaverylongfilenameav.png]
```

Thus, since the forward slash is replaced with an underscore and the image "hash" gets included in the filename it seems that this error shows up when the file name is longer than 255-59 = 196 characters.

**Comment by rovest** [comment]
Hei @motin 

Tusen takk for feedback on this and other issues.

1. Is this a recurring issue, or was it triggered by stress testing code?
2. Do you have a suggestion for a fix, or OK to leave it as a “freak occurrence of very long filename not likely to happen again”?

Thank you for your time.

Ha en god dag,
Hilsen Roar

**Comment by rovest** [comment]
Hi @motin,

Have included a quick-fix in v. 1.7.3 coming soonish:

At line 436 in function: make_text_bundle():
```
    for image in matches:
        if len(image) > 255:
            print(' - Image name too long, so not included in textbundle/assets:')
            print(' -', image)
            continue
```

And at line 464 in function: include_files():
```
    for file in matches:
        if len(file) > 255:
            print(' - File name too long, so not included in textbundle/assets:')
            print(' -', file)
            continue
```

Hope that's good enough for now. 

I could of course leave it as nested path (as on original), but not sure if that's compliant with textbundle spec, and I also have to make changes to (or switch between two) RegEx patterns.

Another solution was to shorten image/filename, but have to keep complete path/file-info, to be able to do roundtrip safe sync-back to Bear.
