### ISSUE TITLE
DB path has changed

### ISSUE THREAD

**Issue by trifle** [rovest/Bear-Markdown-Export#8]
Hi, thanks for the script - this looks extremely useful!

It seems that the path to app data has changed in some recent version of macos. For many apps, the sandboxed data no longer resides in `~/Library/Containers` but rather in `~/Library/Group Containers/`. The specific app path there is also prefixed with a ten character string, e.g. `ABCDEFGHIJ.net.shinyfrog.bear`.

The path to the db and the image folder need to be updated accordingly to make the script work again. I guess that there probably won't be multiple app dirs in the Group Containers folder, so it should be ok to walk or glob that directory and pick the name matching "*.net.shinyfrog.bear".

Cheers!

**Comment by motin** [comment]
I wonder if the ten character string is a fixed id or not. My database is currently located in `~/Library/Group Containers/9K33E3U3T4.net.shinyfrog.bear/Application Data/database.sqlite` on OSX Mojave - @trifle do you have the same path?

**Comment by trifle** [comment]
@motin Interesting, you're right! I have the exact same path (`9K33E3U3T4.net.shinyfrog.bear`), although on High Sierra. That makes it even easier.

**Comment by motin** [comment]
A fix is available in https://github.com/rovest/Bear-Markdown-Export/pull/9
